In [1]:
# add root dir to syspath
import os,sys,inspect
current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent_dir = os.path.dirname(current_dir)
root_dir = os.path.dirname(parent_dir)
sys.path.insert(0, root_dir)

In [2]:
import encoder
import decoder
import discriminator
from imageGenerators import load_realdata

import numpy as np

In [3]:
dims = (512,128)

In [4]:
def normalize_image(image):
    image = image.astype("float32")
    image = (image / 127.5) - 1
    return image

In [5]:
images_real, labels_real = load_realdata.load_wmr_easy(n_toLoad = 10, resizeTo=dims, keepRatio=True, processImage=None, channels=1)

C:\Users\andre\jupyter_ws\imageGenerators\load_realdata.py:62: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv(txt_path, sep=seperators ,header=None)


In [6]:
images_real = np.array([
    normalize_image(image) for image in images_real
])

In [7]:
print(images_real.shape)
image_shape = images_real.shape[1:None]

(10, 128, 512, 1)


In [8]:
encoder_content = encoder.content_model(image_shape)
code_content = encoder_content.predict(images_real)
print(code_content.shape)

(10, 32, 128, 256)


In [9]:
encoder_style = encoder.style_model(image_shape)
code_style = encoder_style.predict(images_real)
print(code_style.shape)

(10, 8)


In [10]:
#adain_params = decoder.mlp(code_style.shape[1], 8)(code_style)

In [11]:
"""adain_params.shape

adain_index=0

gamma = adain_params[:, adain_index]
beta = adain_params[:, adain_index+1]


axis = [1,2]
t = code_content
mean = tf.math.reduce_mean(t, axis=axis, keepdims=True)
std = tf.math.reduce_std(t, axis=axis, keepdims=True)
result = (t - mean) / std
"""

'adain_params.shape\n\nadain_index=0\n\ngamma = adain_params[:, adain_index]\nbeta = adain_params[:, adain_index+1]\n\n\naxis = [1,2]\nt = code_content\nmean = tf.math.reduce_mean(t, axis=axis, keepdims=True)\nstd = tf.math.reduce_std(t, axis=axis, keepdims=True)\nresult = (t - mean) / std\n'

In [12]:
#print(result.shape)
#g = tf.reshape(gamma, (-1, 1, 1, 256) )
#print(gamma.shape)
#x = gamma * result

In [13]:
dec = decoder.model(code_content.shape[1:None], code_style.shape[1:None], 1)

!!! ------------------------
layer-normalization not implemented yet. for now, not using any normalization on upscaling layers. Implement later and compare results
!!! ------------------------
!!! ------------------------
layer-normalization not implemented yet. for now, not using any normalization on upscaling layers. Implement later and compare results
!!! ------------------------


In [14]:
result = dec.predict([code_content, code_style])

In [15]:
result.shape

(10, 128, 512, 1)

In [16]:
disc = discriminator.model(image_shape)

In [17]:
prediction = disc.predict(result)
print(prediction.shape)

(10, 1)


In [18]:
disc_s = discriminator.multiscale_model(image_shape)
prediction = disc_s.predict(result)
print(prediction.shape)

(10, 3)


In [21]:
print(prediction)

[[ 6.73011800e-06  7.54665962e-07 -3.01251112e-06]
 [ 1.54007721e-05  2.01672592e-05  5.76512684e-06]
 [ 6.64161053e-06  1.04686151e-05  2.11001716e-05]
 [-7.06275750e-06  1.02250369e-05  1.17849495e-05]
 [ 4.68221106e-06  1.50058167e-06  6.46831040e-06]
 [ 1.66401351e-05  1.41794953e-05  1.64186476e-05]
 [ 5.17356511e-06 -1.57510385e-06 -9.80326240e-06]
 [-1.91500985e-05 -3.07666232e-06 -2.35374555e-05]
 [-1.04278042e-05 -2.03329218e-05 -9.43543637e-06]
 [-6.24820041e-06 -1.03040611e-05 -1.63328878e-05]]


In [20]:
----

SyntaxError: invalid syntax (<ipython-input-20-759c4c5efcf3>, line 1)

In [ ]:
import tensorflow as tf

In [ ]:
t = tf.constant([
    [1,2,3],
    [2,2,3],
    [3,2,3],
    [4,2,3],
    [5,2,3],
])

print(t)

x = tf.slice(
    t, (0,1), (-1,1)
)

print(x)


In [ ]:
m = tf.math.reduce_mean(t)
print(m)

y = tf.reshape(t, (None,1) )
print(y)

In [ ]:
t = tf.range(0, 100, 1)
t = tf.reshape(t, (10,2,5))
u = tf.range(0, 50, 1)
u = tf.reshape(u, (10,5))
print(t)
print(u)

y = t-u
print(y)